confMap:
  postgresDbName: postgres
  postgresPort: "5432"
  postgresUser: postgres
kubernetesClusterDomain: cluster.local
migratePostgres:
  backoffLimit: 4
  migratePostgres:
    image:
      repository: nikolaygr/otusdelivery
      tag: v0.1
deliveryDp:
  deliveryApp:
    image:
      repository: nikolaygr/otusdelivery
      tag: v0.1
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
deliveryServiceLb:
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
